---
title       : Coursera Developing Data Products Week 4 Assignment, Reproducible Pitch
subtitle    : 
author      : Anagh Das 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Coursera Reproducible Pitch

### See the Regression Models Course Project  

- Find here all the data that have been use for this presentation and also for the first part of the data Science Project: "First, you will create a Shiny application and deploy it on Rstudio's servers.Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application."

### Find all details here
URL:*https://www.coursera.org/learn/data-products/peer/tMYrn/course-project-shiny-application-and-reproducible-pitch*

---
## mtcars Dataset

### Motor Trend Car Road Tests

> The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).

### Source
> Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391-411.
```{r}
library(datasets)
head(mtcars, 3)
```
---
## mtcars Dataset - Format

**A data frame with 32 observations on 11 variables.**

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

--- 
## mtcars Dataset - Format

**A data frame with 32 observations on 11 variables.**

| Index | Field | Detail |
------- | ----- | ------ |
| [, 1] | mpg | Miles/(US) gallon |
| [, 2]  | cyl | Number of cylinders |
| [, 3]	| disp | Displacement (cu.in.) |
| [, 4]	| hp | Gross horsepower |
| [, 5]	| drat | Rear axle ratio |
| [, 6]	| wt | Weight (lb/1000) |
| [, 7]	| qsec | 1/4 mile time |
| [, 8]	| vs | V/S |
| [, 9]	| am | Transmission (0 = automatic, 1 = manual) |
| [,10]	| gear | Number of forward gears |
| [,11]	| carb | Number of carburetors |

--- 
## ui.R

```r
  library(shiny)

shinyUI(
navbarPage("Developing Data Products Assignment",
           tabPanel("Simple Regression",
           (fluidPage(
  titlePanel("Predict Miles per Gallon (mpg) with Simple Regression Models"),
  sidebarLayout(
    sidebarPanel(
      selectInput("variable", "Select Input for Simple Regression",
                  c("am","cyl","hp","wt","disp","drat","qsec","gear","carb")),
      checkboxInput("simple_model","show simple model",value=FALSE),
      submitButton("Submit")
```
---
## 


--- 
## server.R

```r
library(shiny)
library(ggplot2)
library(olsrr)
data(mtcars)

mtcars$cyl <- factor(mtcars$cyl)
mtcars$vs <- factor(mtcars$vs)
mtcars$gear <- factor(mtcars$gear)
mtcars$carb <- factor(mtcars$carb)
mtcars$am <- factor(mtcars$am,labels=c("Automatic","Manual"))

shinyServer(function(input, output) {

  full_model<-lm(mpg ~ am+cyl+hp+wt+disp+hp+drat+qsec+gear+carb,data=mtcars)
  best_model<-lm(mpg ~ am+hp+wt+disp+qsec,data=mtcars)

  formula<-reactive({
    paste("mpg ~", input$variable)

  })
  fit_simple<-reactive({
    lm(as.formula(formula()),data=mtcars)
  })

  output$model<-renderText({
    if(input$simple_model)
    {formula()}
  })

  output$simpleboxplot <- renderPlot({
    # check for the input variable
    if (input$variable == "am") {
      # am
      mpgData <- data.frame(mpg = mtcars$mpg, var = factor(mtcars[[input$variable]], labels = c("Automatic", "Manual")))
      p <- ggplot(mpgData, aes(var, mpg,fill=var)) + 
        geom_boxplot(alpha=0.3) + 
        xlab(input$variable)+scale_fill_brewer(palette="BuPu")
      print(p)

    }
    else if(input$variable == "cyl"|input$variable == "vs"|input$variable == "gear"|input$variable == "carb"){
      # cyl and gear
      mpgData <- data.frame(mpg = mtcars$mpg, var = factor(mtcars[[input$variable]]))
      p <- ggplot(mpgData, aes(var, mpg,fill=var)) + 
        geom_boxplot(alpha=0.3) + 
        xlab(input$variable)+scale_fill_brewer(palette="BuPu")
      print(p)

    }
    else{
      output$simpletext<-renderText({


        if (input$variable!= "am"|input$variable != "cyl"|input$variable!= "vs"|input$variable!= "gear"|input$variable!= "carb"){

          print("We don't have a categorical grouping variable!")
        }

      })

    }

  })

  output$simplesummary<-renderPrint({
    summary(fit_simple())
  })

  output$simpleresidual<-renderPlot({

    par(mfrow = c(2, 2))
    plot(fit_simple())
  })


  output$multisummary<-renderPrint({
    summary(full_model)

  })

  output$multiresidual<-renderPlot({

    par(mfrow = c(2, 2))
    plot(full_model)
  })

  output$bestvariablesubsets<-renderPrint({

    if(input$show)
    {ols_step_best_subset(full_model,details=TRUE)}
    else{"Check Show Hide Best Variable Subsets and Press Submit Button"}

  })

  output$fullmodel<-renderText({

    if(input$multimodel)
      {print("mpg ~ am+cyl+hp+wt+disp+hp+drat+qsec+gear+carb")}
  })

output$variablenumber<-renderPrint({

  if(input$variablenum)
  {adjr<-ols_step_best_subset(fit_multivariable_full,details = TRUE)$adjr
  which(adjr==max(adjr))}
  else{"Check Show Hide Best Variable Number and Press Submit Button"}

})

output$bestvariables<-renderPrint({

  if(input$variables)
  {
    adjr<-ols_step_best_subset(fit_multivariable_full,details = TRUE)$adjr
    var<-ols_step_best_subset(fit_multivariable_full,details = TRUE)$predictors[which(adjr==max(adjr))]
    print(var)
 }
  else{"Check Show Hide Best Variables and Press Submit Button"}

})

output$multisummary2<-renderPrint({
  summary(best_model)


})
output$multiresidual2<-renderPlot({

  par(mfrow = c(2, 2))
  plot(best_model)
})
})

```
---
